### ISSUE TITLE
INVD cannot be enabled

### ISSUE THREAD

**Issue by Szy0127** [cispa/CacheWarp#1]
I tried your cmd on AMD EPYC 7T83 and AMD EPYC 9354, both failed.
```
$ sudo bash -c 'modprobe msr; CUR=$(rdmsr 0xc0010015); ENABLED=$(printf "%x" $((0x$CUR & ~16))); wrmsr -a 0xc0010015 0x$ENABLED'
wrmsr: CPU 0 cannot set MSR 0xc0010015 to 0x00000000cb006001
```
And I tried to use `wrmsr` and `rdmsr`  instructions by asm in a kernel module, the kernel will panic after installing the kernel module.

**Comment by Jdkhnjggf** [comment]
Hi Szy,

Please check the microcode version and firmware image on your Zen3 machine to see if the patch has been applied. While we've not tested this, what you describe is consistent with our hypothesis about the patch (i.e. cannot modify this MSR bit anymore).

For Zen4, AMD claims that they are not affected by this issue. I'll fix the documentation.

**Comment by Szy0127** [comment]
> Hi Szy,
> 
> Please check the microcode version and firmware image on your Zen3 machine to see if the patch has been applied. While we've not tested this, what you describe is consistent with our hypothesis about the patch (i.e. cannot modify this MSR bit anymore).
> 
> For Zen4, AMD claims that they are not affected by this issue. I'll fix the documentation.

The microcode is 0xa0011d1 and I'm afraid the patch is applied since I can modify any other bit except bit 4.
It's a pity that I'm not able to reproduce your nice work.

**Comment by Jdkhnjggf** [comment]
Thanks:) An oldest microcode version in the bios could be used (downgrade) by adding `dis_ucode_ldr` to the kernel command line if you're still interested in it.
